### ISSUE TITLE
Consider updating html5lib version dependency

### ISSUE THREAD

**Issue by taisph** [angular/angular.dart#1281]
Testing suggests html5lib pubspec dependency can be expanded to <0.12.0, which would be helpful for people trying to use angular with polymer, core_elements etc.

I've bumped the version dependency locally and run the scripts/run-test.sh script as well as basic usage tests in my own Angular-based project. No code was harmed during this experiment.

pubspec.yaml

```
name: angular
version: 0.13.0
authors:
- Misko Hevery <misko@hevery.com>
- Pavel Jbanov <pavelgj@gmail.com>
- James deBoer <james@huronbox.com>
- Chirayu Krishnappa <chirayu@google.com>
- Matias Niemela <matias@yearofmoo.com>
- Paul Rohde <paul@paulrohde.com>
- Victor Berchet <victor@suumit.com>
description: Angular for dart.
homepage: https://angulardart.org
environment:
  sdk: '>=1.4.0'
dependencies:
  args: '>=0.10.0 <0.11.0'
  analyzer: '>=0.15.0 <0.19.0'
  barback: '>=0.13.0 <0.17.0'
  browser: '>=0.10.0 <0.11.0'
  code_transformers: '>=0.1.4+2 <0.2.0'
  collection: '>=0.9.1 <1.0.0'
  di: '>=2.0.1 <3.0.0'
  html5lib: '>=0.10.0 <0.12.0'
  intl: '>=0.8.7 <0.12.0'
  perf_api: '>=0.0.8 <0.1.0'
  route_hierarchical: '>=0.4.21 <0.5.0'
  web_components: '>=0.3.3 <0.4.0'
dev_dependencies:
  benchmark_harness: '>=1.0.0 <2.0.0'
  guinness: '>=0.1.9 <0.2.0'
  mock: '>=0.10.0 <0.12.0'
  protractor: '0.0.5'
  unittest: '>=0.10.1 <0.12.0'
```

pub deps

```
angular 0.13.0
|-- analyzer 0.18.0
|   |-- args...
|   |-- logging...
|   |-- path...
|   '-- typed_mock 0.0.4
|-- args 0.10.0+2
|   '-- collection...
|-- barback 0.14.0+3
|   |-- collection...
|   |-- path...
|   |-- source_maps...
|   '-- stack_trace 0.9.3+2
|       '-- path...
|-- benchmark_harness 1.0.4
|   '-- browser...
|-- browser 0.10.0+2
|-- code_transformers 0.1.6
|   |-- analyzer...
|   |-- barback...
|   |-- path...
|   '-- source_maps...
|-- collection 0.9.4
|-- di 2.0.1
|   |-- analyzer...
|   |-- barback...
|   |-- code_transformers...
|   '-- path 1.2.2
|-- guinness 0.1.13
|   |-- collection...
|   '-- unittest...
|-- html5lib 0.11.0+2
|   |-- csslib 0.11.0
|   |   |-- args...
|   |   |-- logging...
|   |   |-- path...
|   |   '-- source_span 1.0.0
|   |       '-- path...
|   |-- source_maps 0.9.3
|   |   '-- path...
|   '-- utf 0.9.0+1
|-- intl 0.8.10+4
|   |-- analyzer...
|   |-- path...
|   '-- meta 0.8.8
|-- mock 0.11.0+2
|   '-- matcher 0.11.0
|-- perf_api 0.0.8
|-- protractor 0.0.5
|   '-- js 0.2.2
|       '-- browser...
|-- route_hierarchical 0.4.21
|   |-- browser...
|   '-- logging 0.9.2
|-- unittest 0.11.0+3
|   |-- matcher...
|   '-- stack_trace...
'-- web_components 0.3.5+1
```
