### ISSUE TITLE
Build size is very big

### ISSUE THREAD

**Issue by cinan** [angular/angular.dart#1471]
I build application with command `pub build web`. Size of `main.dart.js` is 4.6MB. While building application there are warnings about `@MirrorUsed`:

```
web/main.dart:
7195 methods retained for use by dart:mirrors out of 14503 total methods (50%).
Info from Dart2JS on staffino_frontend|web/main.dart:
packages/angular/animate/module.dart:116:1:
This import is not annotated with @MirrorsUsed, which may lead to unnecessarily large generated code.
Try adding '@MirrorsUsed(...)' as described at https://goo.gl/Akrrog.
import 'dart:mirrors' show MirrorsUsed;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Info from Dart2JS on staffino_frontend|web/main.dart:
packages/di/src/mirrors.dart:3:1:
This import is not annotated with @MirrorsUsed, which may lead to unnecessarily large generated code.
Try adding '@MirrorsUsed(...)' as described at https://goo.gl/Akrrog.
import 'dart:mirrors';
^^^^^^^^^^^^^^^^^^^^^^
Info from Dart2JS on staffino_frontend|web/main.dart:
packages/json_object/json_object.dart:12:1:
This import is not annotated with @MirrorsUsed, which may lead to unnecessarily large generated code.
Try adding '@MirrorsUsed(...)' as described at https://goo.gl/Akrrog.
import 'dart:mirrors' as mirrors;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Info from Dart2JS on staffino_frontend|web/main.dart:
packages/reflection/reflection.dart:4:1:
This import is not annotated with @MirrorsUsed, which may lead to unnecessarily large generated code.
Try adding '@MirrorsUsed(...)' as described at https://goo.gl/Akrrog.
import 'dart:mirrors';
^^^^^^^^^^^^^^^^^^^^^^
```

Here's pubspec.yaml:

```
name: test
version: 0.0.1
dependencies:
  angular: ">=0.14.0 <0.15.0"
  browser: any
  web_components: any
  json_object: any
  crypto: any
  dart_config: any
  queries: any
  quiver: any
dev_dependencies:
  unittest: any
  mock: any
  dartmocks: any
transformers:
- angular:
    dart_sdk: /opt/google/dartsdk/
    html_files:
    - web/index.html
    - web/views/login.html
    - web/views/in.html
    - web/views/profile.html
    - web/views/feedbacks.html
    - web/views/team.html
    - web/views/venue.html
    - web/views/statistics.html
    - web/views/statistics/dashboard.html
    - web/views/statistics/users.html
    - lib/components/chosen/chosen_component.html
    - lib/components/dial_graph/dial_graph_component.html
    - lib/components/error_msg/error_msg_component.html
    - lib/components/file_upload/file_upload_component.html
    - lib/components/menu/menu_component.html
```

and here's pubspec.lock:

```
# Generated by pub
# See http://pub.dartlang.org/doc/glossary.html#lockfile
packages:
  analyzer:
    description: analyzer
    source: hosted
    version: "0.18.0"
  angular:
    description: angular
    source: hosted
    version: "0.14.0"
  args:
    description: args
    source: hosted
    version: "0.10.0+2"
  barback:
    description: barback
    source: hosted
    version: "0.14.2"
  browser:
    description: browser
    source: hosted
    version: "0.10.0+2"
  code_transformers:
    description: code_transformers
    source: hosted
    version: "0.1.6"
  collection:
    description: collection
    source: hosted
    version: "0.9.4"
  collection_helpers:
    description: collection_helpers
    source: hosted
    version: "0.9.1"
  crypto:
    description: crypto
    source: hosted
    version: "0.9.0"
  dart_config:
    description: dart_config
    source: hosted
    version: "0.5.0"
  dartmocks:
    description: dartmocks
    source: hosted
    version: "0.5.2"
  di:
    description: di
    source: hosted
    version: "2.0.2"
  html5lib:
    description: html5lib
    source: hosted
    version: "0.10.0"
  intl:
    description: intl
    source: hosted
    version: "0.11.7"
  json_object:
    description: json_object
    source: hosted
    version: "1.0.18+2"
  logging:
    description: logging
    source: hosted
    version: "0.9.2"
  matcher:
    description: matcher
    source: hosted
    version: "0.10.1+1"
  mock:
    description: mock
    source: hosted
    version: "0.11.0+2"
  path:
    description: path
    source: hosted
    version: "1.3.0"
  perf_api:
    description: perf_api
    source: hosted
    version: "0.0.9"
  petitparser:
    description: petitparser
    source: hosted
    version: "1.2.2"
  pool:
    description: pool
    source: hosted
    version: "1.0.1"
  queries:
    description: queries
    source: hosted
    version: "0.0.14"
  quiver:
    description: quiver
    source: hosted
    version: "0.18.2"
  reflection:
    description: reflection
    source: hosted
    version: "0.0.24"
  route_hierarchical:
    description: route_hierarchical
    source: hosted
    version: "0.4.22"
  source_maps:
    description: source_maps
    source: hosted
    version: "0.9.4"
  source_span:
    description: source_span
    source: hosted
    version: "1.0.0"
  stack_trace:
    description: stack_trace
    source: hosted
    version: "1.0.2"
  string_scanner:
    description: string_scanner
    source: hosted
    version: "0.1.0"
  typed_mock:
    description: typed_mock
    source: hosted
    version: "0.0.4"
  unittest:
    description: unittest
    source: hosted
    version: "0.11.0+5"
  utf:
    description: utf
    source: hosted
    version: "0.9.0+1"
  web_components:
    description: web_components
    source: hosted
    version: "0.7.0"
  yaml:
    description: yaml
    source: hosted
    version: "2.0.1+1"
```
