### ISSUE TITLE
css-shim: specificity issues with :host

### ISSUE THREAD

**Issue by BlackHC** [angular/angular.dart#1569]
Hello,
we have the following problem:

``` scss

.our-root {
  .our-input {
    background-position: right 2px top 2px;

    :host[dir=rtl] & {
      background-position: left 2px top 2px;
    }
  }
}
```

gets rewritten to:

``` scss
.our-root[our-component] .our-input[our-component] {
  background-position: right 2px top 2px;
}

our-component[dir=rtl] .our-root .our-input {
  background-position: left 2px top 2px;
}
```

So, suddenly the parent class has a higher specificity than the child (4 class/attribute selectors vs 3).

Would it be possible to change the shim to add [our-component] to the non-:host elements in the rule? That is to obtain: `our-component[dir=rtl] .our-root[our-component] .our-input[our-component]`

That would make the css-shim order-preserving (regarding specificity within the same component) which would be a nice thing to have ^^

What do you think?
