### ISSUE TITLE
Cannot add comments before polyfill-unscoped-next-selector.

### ISSUE THREAD

**Issue by heyhae** [angular/angular.dart#1570]
Just noticed that if there is a comment before polyfill-unscoped-next-selector,
css_shim.dart cannot recognize polyfill-unscoped-next-selector.

``` css
/* adding comments before polyfill-unscoped-next-selector breaks */
polyfill-unscoped-next-selector {
  content: '[my-component] .my-stuff';
} /deep/ .my-stuff {
  ...
}
```

generates something like:

``` css
/*[my-component] adding[my-component] comments[my-component] before[my-component] polyfill-unscoped-next-selector[my-component] breaks[my-component] */
polyfill-unscoped-next-selector[my-component] {
  content: '[my-component] .my-stuff'; }
.my-stuff[my-component] {
  ... }
```

polyfill-unscoped-next-selector is completely ignored.
It is also kinda weird that [my-component] is appended to comments...
