### ISSUE TITLE
Hierarchical binding problem

### ISSUE THREAD

**Issue by cgarciae** [angular/angular.dart#1615]
I have this hierarchical structure `MyComponent -> A -> B -> String` (as you can see below) that attempts to bind `a.b.text` to a input box, on `MyComponent`'s template
```
@ng.Injectable()
class B {
    String text;
}

@ng.Injectable()
class A {
    B b;

    A (this.b);
}

@ng.Component(
    selector : "my-component",
    template: '{{a.b.text}} Name: <input type="text" ng-model="a.b.text">'
)
class MyComponent {
    A a;

    MyComponent(this.a);
}
```
I get this error

```
Missing getter: (o) => o.b
...
Exception: The null object does not have a method 'call'.
NoSuchMethodError: method not found: 'call'
Receiver: null
Arguments: [Instance of 'A']
```
My module configuration is

```
class MyAppModule extends Module {
    MyAppModule() {
        bind (EventoComponent);
        bind (A);
        bind (B);
    }
}

//Inside main()
applicationFactory()
    .addModule(new MyAppModule())
    .run();

```

and `pubspec` file

```
name: restonetest
description: A sample web application
dependencies:
  angular: any
  appengine: any
  browser: any
  di: any
  fp: any
  redstone: any
  redstone_mapper: any
  shelf_static: any
transformers:
- redstone_mapper
- angular:
    html_files:
    - lib/client/models/evento/evento.html
```
