### ISSUE TITLE
Upgrade html5lib dependencies

### ISSUE THREAD

**Issue by MikeMitterer** [angular/angular.dart#883]
Guys, please upgrade your polymer-dependencies.

Here are my dependencies:

```
dependencies:
  polymer_elements:
    git: https://github.com/ErikGrimes/polymer_elements

  polymer_ui_elements:
    git: https://github.com/ErikGrimes/polymer_ui_elements

  angular:
    git: https://github.com/angular/angular.dart
```

And this is what I get:

```
Resolving dependencies... (15.9s)
Incompatible version constraints on html5lib:
- angular depends on version >=0.9.2 <0.10.0
- polymer depends on version >=0.10.0 <0.11.0
```
